# Analyis the results of outMCScalc generated by previous R script.
# Songpeng Zu
# 2015-06-08

#- load package
library(fmcsR)
library(ChemmineR)
library(xlsx)
#- load file
MCSmat <- read.table("outMCScalc.txt",header=FALSE, sep="\t")
cidsNotSure <- read.xlsx("CompoundsIdentify_150528.xlsx",2,header=FALSE,
                         colIndex = 1)
cidsAll <- read.xlsx("CompoundsIdentify_150528.xlsx",1,header=FALSE,
                     colIndex = 1)
cidsAllothers <- setdiff(cidsAll[[1]],cidsNotSure[[1]])
compoundsNotSure <- getIds(cidsNotSure[[1]])
compoundsAllOthers <- getIds(cidsAllothers)

#- find max
MCSmaxpos <- apply(MCSmat,1,which.max)
MCSmaxindex <- cidsAllothers[MCSmaxpos]
MCSmaxscore <- apply(MCSmat,1,max)

#- plot
# rename the print_cid of these compounds as their cids.
# A bug: if you set cid(sdfset) <- st
# The function of cid(sdfset) returns the previous value. But str(sdfset)
# you would find multi @IDs. And if you cid(sdfset) <- st for more than three
# times, each time it would create a ID. And, fmcs return error.
cid(compoundsNotSure) <- sdfid(compoundsNotSure)
cid(compoundsAllOthers) <- sdfid(compoundsAllOthers)

pdf("MCSmaxplot.pdf",width=12,height=7)
for(i in 1:length(cidsNotSure$X1)){
    plotMCS(fmcs(compoundsNotSure[i],compoundsAllOthers[MCSmaxpos[i]]),
            atomcex=0.8,bondspacer=0.05,regenCoords=TRUE)
}
dev.off()
